# Numpy(2)
- 계산을 위해 array의 모양을 자동적으로 맞춰주는게 중요하다.
- 벡터 기반으로 데이터를 처리하는 라이브러리
- array 기반이다.

In [1]:
import numpy as np

### info()말고 정보 보는 법 - 중요! ★★

In [5]:
np.lookfor('* array')

Search results for '* array'
----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.modf
    Return the fractional and integral parts of an array, element-wise.
numpy.rint
    Round elements of the array to the nearest integer.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.isnan
    Test element-wise for NaN and return result as a boolean array.
numpy.isnat
    Test element-wise for NaT (not a time) and return result as a boolean array.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, ele

0차 배열 - 스칼라 값

In [6]:
a = np.array(100)

In [7]:
a

array(100)

[]로 묶어줘야 최소 1차

In [8]:
a = np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [10]:
a = np.array([[1,2,3],[4,5,6]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

sum, avg등으로 하나의 값으로 축약 -> reduction

### 모양 바꾸기★★★
1. reshape : stride 개념을 이용하기 때문에 거의 realtime으로 변환이 가능하다.
    - 뮤터블 펑션이 아니기 때문에 자신이 바뀌지 않는다.

In [12]:
a = np.arange(27)

In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [15]:
a.shape

(27,)

reshape 하려면 개수를 맞춰야한다.

In [17]:
a.reshape(4,9)

ValueError: cannot reshape array of size 27 into shape (4,9)

In [18]:
a.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

reshape는 자기 자신이 뮤테이션 되는 함수가 아니다. 그러므로 계속 사용할 거면 재할당 해야한다.

In [19]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

reshape는 참조를 같이 가지고 있기 때문에 바뀌면 기존 것도 같이 바뀌기 때문에 copy 사용해야한다.

In [20]:
b = a.reshape(3,9)

In [21]:
b[0][0] = 100

In [22]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

copy를 사용해서 막아야한다.

In [23]:
b = a.reshape(3,9).copy()

-1을 사용하면 자동으로 정해준다. 

In [24]:
b = a.reshape(3,-1)

In [26]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [27]:
b = a.reshape(-1,9)

In [28]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

-1은 2개 사용할 수 없다.

In [29]:
b = a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

\-(마이너스) 만 사용하면 자동으로 해주는데 갈래상 -1사용

In [30]:
b = a.reshape(3, -100)

In [31]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

resize는 자기 자신이 변하는 뮤테이션 펑션이다.

In [32]:
a.resize((3,9))

In [33]:
a

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

크기를 안 맞춰주면 잘린다.

In [41]:
a = np.arange(27)

In [38]:
a.resize((3,5))

In [39]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

크기가 크게 리사이즈 하면 빈 만큼 0이 채워진다.

In [42]:
a.resize((3,10))

In [43]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0]])

resize는 음수를 지원하지 않는다

In [44]:
a.resize((3,-1))

ValueError: negative dimensions not allowed

## 쪼개고 합치기 ★★★

#### split : 모양을 쪼개줌
3가지가 있다.
- split, vsplit, hsplit

In [45]:
a = np.arange(27)

In [46]:
a = a.reshape(3,9)

In [47]:
'split' in dir(a)

False

In [49]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

자르는 기준 (1,2) : 0~1, 1~2, 2~끝

In [52]:
np.split(a,(1,2))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [53]:
np.split(a,(2,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [54]:
np.split(a, (2,5))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

기준점이 0이므로 -를 넣으면 0에서 잘린다.
- 에러가 안 나므로 잘 알고 있어야한다.

In [55]:
np.split(a, (-2, 5))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [58]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [59]:
np.split(a, (5,5), axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [60]:
np.hsplit(a,(5,))

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [61]:
np.vsplit(a, (2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

#### stack : 합치기

In [63]:
b = np.arange(5)
c = np.arange(5, 10)

In [64]:
np.stack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.stack((b,c),1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [70]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
# matlab? 에 많이 있다. r_는 hstack과 같음
np.r_[b,c]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
#c_는 vstack과 같음
np.c_[b,c]

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [74]:
# s_는 슬라이스 객체를 만들어준다.
np.s_[1,3]

(1, 3)

In [76]:
# s_는 슬라이스 객체를 만들어준다.
np.arange(10)[np.s_[1]]

1

In [73]:
[1,2,3,4,5,][slice(1,5)] # == [1,2,3,4,5,][1:5]

[2, 3, 4, 5]

In [77]:
np.column_stack([b,c])

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### newaxis : 골치 아픈애! :O

In [78]:
a = np.arange(6)

In [79]:
a

array([0, 1, 2, 3, 4, 5])

이거를 만들고 싶다.

In [86]:
a = np.array([[0,1,2,3,4,5]])

In [85]:
a

array([[0, 1, 2, 3, 4, 5]])

In [80]:
a = a.reshape(6,1)

In [81]:
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [87]:
a[np.newaxis]

array([[[0, 1, 2, 3, 4, 5]]])

In [89]:
np.newaxis == None

True

보기 좋지 않으므로 None을 정의해서 사용한다.

In [90]:
a[None]

array([[[0, 1, 2, 3, 4, 5]]])

In [91]:
np.newaxis is None

True

In [94]:
a = np.arange(6)
a = a.reshape(2,3)

In [93]:
a[np.newaxis]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [95]:
a[:,np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [96]:
a[:, :,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [97]:
a = np.arange(6)

In [98]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

#### newaxis가 골치아프므로 expand_dims이라는 메서드가 존재한다.
- 차원을 하나씩만 바꿔줄 수 있다.

In [99]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [102]:
np.expand_dims(a,2)

C:\Anaconda\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [103]:
np.expand_dims(a,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
a = np.arange(27).reshape(3,3,3)

In [105]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

자유 자제로 바꿀 수 있게 하는 메서드들

In [106]:
np.swapaxes(a, 0, 2)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [107]:
np.moveaxis(a, 0,2)

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

## Structured Array ★★★★
- 이것을 기반으로 판다스를 만들었다.
- 넘파이에서는 사용자 정의 데이터를 어떻게 만들 것인가?
    - 튜플 형태로 (이름, 타입)으로 만든다.
- 정형화된 데이터를 만들고 싶을 때 사용한다.
- DB처럼 사용할 수 있다.
- 메모리에 올리므로 아주 빠르게 사용할 수 있다.
    - 메모리에 올리지 못할 때 해결할 수 있는 방법이 있다.

In [108]:
a = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [109]:
a

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [110]:
a[0]

('Rex', 9, 81.)

#### named tuple
- 클래스 만드는 방법과 같다.
- 변수 접근 방법, 인덱스 방법 두가지로 접근할 수 있다.
- DB에서 row개념으로 사용하고 싶을 때 빠르게 만들 수 있다
- Structured Array와 유사하다

In [111]:
from collections import namedtuple

In [116]:
Address = namedtuple('Address', ('name','age','weight'))

In [117]:
a1 = Address('Rex', 27, 81.0)

In [118]:
a1.name

'Rex'

In [120]:
a1

Address(name='Rex', age=27, weight=81.0)

count와 index는 튜플에 사용하는 애. 그 이외에 name, age, weight를 어트리뷰트로 가지고 있다.

In [121]:
dir(a1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'age',
 'count',
 'index',
 'name',
 'weight']

In [122]:
a1[0]

'Rex'

인덱스로 접근할 수 있는 것은 키로 접근할 수 없다

In [124]:
a1['name']

TypeError: tuple indices must be integers or slices, not str

Structured Array는 key로 딕셔너리처럼 접근할 수 있다.
- 컬럼 데이터를 모두 가져온다.

키로 접근 - 키에 해당하는 값들을 모두 가져온다.

In [125]:
a['name']

array(['Rex', 'Fido'], dtype='<U10')

어트리뷰트 방식으로는 접근 못한다.

In [126]:
a.name

AttributeError: 'numpy.ndarray' object has no attribute 'name'

In [129]:
'name' in dir(a)

False

dtype에 데이터 타입의 이름을 지정할 때 문자열로만 불러야 한다. 숫자 사용 불가

In [134]:
a = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)], dtype=[(0, 'U10'), ('age', 'i4'), ('weight', 'f4')])

TypeError: data type not understood

In [132]:
a

array([('0', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])