# NumPy
- 넘파이가 있어서 데이터 분석을 파이썬으로 할 수 있게 됐다.
- 파이썬은 속도가 느리다는 단점이 있다.
    1. 좋은 컴퓨터를 써서 보완한다.
    2. gp, gpu를 사용하거나 분산환경을 사용한다.(돈이 많이 든다.)
    3. Cython -> 자료 형태 지정 C처럼 파이썬을 사용. C 속도에 근접하게 나온다. 컴파일 할 수 있어서 빠름.
    4. PyPy -> Python으로 만든 Python: 파이썬보다 5배정도 빠르다.(최적화 되어있음) 문법 수정할 필요가 없다. 호환성 문제가 있음.
    5. 프로파일링 기법 -> 파이썬은 glue language이므로 다른 언어랑 잘 붙는다. 병목 현상이 일어나는 부분에 다른 언어를 붙여서 해결 : 공식적으로 C랑 붙이는 것으로 되어있다.
    6. Algorithm / DataStructure -> 특히 계산에서 속도가 빠르게 만든 것이 numpy이다. python보다 5~20배 빠르다. 
- 속도가 빠르고 편하고 쉽기 때문에 사용한다.
- 넘파이를 기반으로 판다스, 텐서플로우, 사이킷, 파이토치를 만들었다.(넘파이가 로우레벨)
- 왜 속도가 빠를까?
    - C로 만들어져 있고 벡터라이제이션으로 만들어있다.
    - vetorization(벡터화): CPU 자체에서 최적화로 벡터화 해준다. 넘파이는 CPU를 지원하지 않는다. -> CPU 지원하는 기능을 추가한 것이 텐서, 파이토치
        - 행렬 사용하는 이유: 한 번에 여러 값을 계산할 수 있다.
        - 벡터 = Array : 여러개의 데이터를 한 묶음으로 만드는 애
        - loop가 없다. (loop를 사용하면 느려진다) : 이터레이터/제너레이터, 컴프리헨션, 재귀, map, reduce, filter -> array programming(for를 사용하지 않고 반복을 처리)
- 숫자가 크면 클 수록 빠르다. -> 작은 양에서는 속도가 느릴 수 있다. (항상 array programming을 사용하는 것은 아님)
- 넘파이만 사용하는 연산이 있다.

## Array
- 1차원 벡터는 방향이 없다고 생각하자
- 2차원 matrix
- 3차원 3D array(Tensor)

...
- N차원 ND array

- 어떤 현상을 벡터화 시키는 것이 핵심

In [1]:
import numpy as np

In [2]:
# 대문자 ascii 65 소문자 ascii 97 이므로 대문자 먼저
# 대문자로 된 어트리뷰트 -> 파이썬은 상수가 없지만 갈래상 상수처럼 사용 
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

객체 만드는 방식 3가지
1. 리터럴사용 -> 파이썬에서 지원해주는 고유 자료형 정의
2. 인스턴스화 해서 객체 생성
3. 팩토리 메소드 - 인스턴스화 하지 않고 다른 함수의 힘을 빌어서 인스턴스화 한다.

- 파이썬 공식 라이브러리에도 array가 존재한다. (사용 안함)
- array는 homogeneous : 다음에 오는 데이터 타입을 확인할 필요가 없으므로 속도가 빠르다.

In [ ]:
import array

array는 데이터가 한 개 이상

In [4]:
a = np.array(1)

In [5]:
a

array(1)

In [6]:
a = np.array([1,2])

In [7]:
a

array([1, 2])

튜플을 넣어도 리스트가 나온다.
- array는 뮤터블이다.
- 뮤터블에서 나오는 문제를 가지고 있다.
    - 자신이 변하고 값을 반환
    - 자신이 변하고 아무것도 반환하지 않는 경우
- 스왈로우카피, 딥카피 사용.

In [8]:
a = np.array((1,2))

In [9]:
a

array([1, 2])

ndarray : n차원 array
- array()로 나오는 것은 넘파이의 array다.

In [10]:
type(a)

numpy.ndarray

In [11]:
a = np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

3차원에서 빈공간 : 직사각형 판이 여러개가 있다. 판 하나마다 공백이 있는 것.

In [13]:
a = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])

In [14]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

무한 차원까지 늘릴 수 있다.

인스턴스화 해서 만들 수 있다.
- ndarray은 array와 미묘하게 다르다.
    - array()는 펙토리 메소드여서 다른 자료형을 homogeneous하게 바꿔준다.
    - ndarray는 인스턴스화여서 다른 자료형을 넣으면 type error가 발생한다.

In [15]:
n = np.ndarray(0)

In [16]:
n

array([], dtype=float64)

팩토리 메서드 방식에서는 array가 homogeneous이므로 자료형이 다르면 하나의 데이터 타입으로 바꿔준다.

In [17]:
a = np.array(['1', 2, 3])

dtype : 리틀 엔디안(<) / 빅 엔디안(>) 
- 저장방식
- numpy는 C로 만들었기 때문에 dtype을 C data type처럼 만들 수 있다.
    -> 메모리 확보와 속도를 최적화 할 수 있다.

In [18]:
a

array(['1', '2', '3'], dtype='<U1')

인스턴스화 방식으로 만들 때 데이터 타입이 다르면 타입 에러가 난다.

In [19]:
a = np.ndarray([0,'1'])

TypeError: 'str' object cannot be interpreted as an integer

In [23]:
a = np.array(["1", 2, 3])

In [24]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [25]:
vars(a)

TypeError: vars() argument must have __dict__ attribute

In [26]:
a = np.array([[1,2],[3,4]])

.ndim 을 사용하면 차원을 알 수 있다.

In [28]:
a.ndim

2

len()도 차원을 알 수 있다.

In [29]:
len(a)

2

자세한 구조를 알고 싶을 때 
- 행렬 연산에서는 모양을 맞춰야하므로 shape가 중요하다.
- shape를 알면 ndim, size를 다 알 수 있다.

In [30]:
a.shape

(2, 2)

flags 사용하면 C 방식으로 저장 되어있는지 Fortran 방식으로 저장 되어있는지 알 수 있다.
- C 형식으로 저장 되면 1, 2, 3 4 순서로 저장
- Fortran 형식으로 저장되면 1, 3, 2, 4 순서로 저장

In [32]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

size : 원소의 개수

In [33]:
a.size

4

itemsize : 각 원소 하나가 몇 바이트인가

In [34]:
a.itemsize

4

dtype : 데이터 타입
- dtype을 알면 itemsize를 알 수 있다. 
- int32면 4바이트 

In [35]:
a.dtype

dtype('int32')

element wise 방식이므로 연산할 때 각각의 원소 끼리 계산을 해준다.
- 훨씬 편하게 벡터 연산을 할 수 있다.
- 기존 파이썬에서는 반복문을 사용해야 한다.

In [36]:
b = np.array([[1,2],[3,4]])

In [39]:
a + b

array([[2, 4],
       [6, 8]])

리스트는 +연산하면 뒤에 붙인다.

In [37]:
x = [1,2,3,4]
y = [2,3,4,5]

In [38]:
x + y

[1, 2, 3, 4, 2, 3, 4, 5]

리스트는 벡터 연산을 하려면 다음과 같이 만들어줘야한다.

In [43]:
[a+b for a,b in zip(x,y)]

[3, 5, 7, 9]

In [45]:
a - b

array([[0, 0],
       [0, 0]])

In [46]:
a * b

array([[ 1,  4],
       [ 9, 16]])

행과 열을 바꾸는 함수

In [47]:
a.T

array([[1, 3],
       [2, 4]])

#### 빠른 이유 3가지
1. 호모지니어스
2. C로 만들었고 효율적인 자료구조
    - 1열로 저장하고 strides로 보여주기 때문
    - homogeneous
3. 벡터라이제이션

##### 상세 이유
- 리스트는 링크드리스트로 구현되어있으므로 따로따로 저장되어있어 찾아가야하며 타입이 다르므로 타입도 체크해야 한다.
- 넘파이는 순서대로 저장 되어있고, 한가지 데이터타입으로 되어있으므로 몇번째인지만 찾으면됨
    - 헤더에 데이터 타입이 저장되어있음.
    - strides 12, 4 -> 3개가 1열 (내부구조가 1열이므로 도입해서 사람들에게 보여줄 때 3행 3열로 보여줌)
    - C의 고급 기법으로 만들었다.

#### SciPy 
- 넘파이 기반으로 과학에 많이 사용되는거를 만들어놨다.
- 가져다 쓰면 된다.

#### stride ★★★
- (row 넘어갈 때 필요한 바이트, column 넘어갈 때 필요한 바이트)
    - 앞의 값을 뒤의 값으로 나누면 몇 열짜리 행인지 알 수 있다.
- 모든 데이터를 1번만에 접근할 수 있다.
- 최소 바이트 단위
- 빠르게 접근할 수 있다.
- 차원이 중요하지 않은 경우에는 strides가 숨어있다.
- C 방식일 때와 fortran일 때 다르다. 
    - C : stride(12, 4)
    - fortran : stride(4, 12)

In [51]:
# 8 / 4 = 2
# 2개가 1행 4개->2행2열
a.strides

(8, 4)

\_(a): 다국어 처리

이름_ : 파이썬 키워드와 같을때 이름 충돌을 방지하기 위해 붙임

#### 쉬운 이유
1. 데이터 타입
    - dtype을 지정만해주면 알아서 처리한다.
    - dtype 변환을 쉽게 할 수 있다.
    - int를 더 쪼개서 사용한다.
    - int, long, longlong, unsigned int 등을 지원해준다.
    - str3가지형에 little 엔디안, big 엔디안까지 지원해준다.
    - Type Code를 이용하여 쉽게 접근할 수 있다.
2. 자동 최적화
    - 넘파이로 만들면 최적화 되므로 최적화 과정이 필요 없다.
3. 인덱싱
4. 브로드캐스팅
5. ufunc

자료형 지정
- 단축 표현을 사용할 수 있다.

In [52]:
a = np.array([[1,2],[3,4]], dtype="i1")

In [53]:
a

array([[1, 2],
       [3, 4]], dtype=int8)

In [54]:
a = np.array([[1,2],[3,4]], dtype="u1")

In [55]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

sctypeDict : 타입의 종류

In [59]:
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [57]:
len(np.sctypeDict)

152

In [58]:
# 몇 비트 짜리인지 확인할 수 있음
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda/A

#### axis ★★★
- 행끼리 계산하는 것은 axis=0 ↓, 열끼리 계산하는 것은 axis=1 →
    - 아주 속도가 빠르다. -> stride 개념이 있기 때문에

- range(x,y) x~ y까지 만들어주는 것
- arange range와 유사

In [61]:
a = np.arange(10)

In [62]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

넘파이에서의 뮤터블
- reshape는 카피개념이므로 재할당 해줘야한다.

In [63]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a = a.reshape(2,5)

In [66]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
a.shape

(2, 5)

axis 개념을 이용하면 내가 원하는 것만 뽑아서 계산할 수 있다.

In [67]:
a.sum()

45

In [69]:
a.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [70]:
a.sum(axis=1)

array([10, 35])

In [72]:
a.mean()

4.5

In [73]:
a.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [74]:
a.mean(axis=1)

array([2., 7.])

In [83]:
%time sum(range(10000000))

Wall time: 933 ms


49999995000000

In [84]:
%time np.sum(np.arange(10000000))

Wall time: 69 ms


-2014260032

### 데이터 만들기
1. ndarray() : 인스턴스 방식
2. np.array() : 팩토리 메서드 방식
3. zeros() : 0값을 넣어서 만들 수 있다.
    - ones() : 1값을 넣어서 만들 수 있다.
    - full() : 원하는 같은 값을 넣어서 만들 수 있다.

In [89]:
a = np.zeros((3,4))

In [90]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
b = np.ones((3,3))

In [98]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
c = np.full((3,2),6)

In [96]:
c

array([[6, 6],
       [6, 6],
       [6, 6]])

likes : 크기를 맞춰서 만들어준다.
- 연산할 때 크기가 중요하다.

In [101]:
d = np.ones_like(a)

In [102]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

단위 행렬
- eye는 좀 더 옵션이 있음
- identity : 쉽게 빨리 만들 수 있다.

In [103]:
b = np.eye(3)

In [104]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
c = np.identity(3)

In [106]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

상삼각행렬, 하삼각행렬

In [109]:
b = np.tri(3)

In [110]:
b

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [112]:
c = np.triu((3,3))

In [113]:
c

array([[3, 3],
       [0, 3]])

전체 행렬

In [114]:
b.T

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [115]:
np.transpose(b)

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

직교 행렬
- orthogonal

0부터 99까지를 n등분

In [118]:
d = np.linspace(0, 99)

In [117]:
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

위의 것을 로그 씌운 것

In [119]:
e = np.logspace(1,100)

In [120]:
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

empty
- 쓰레기값이 들어있는 것.
- 초기화가 되어있지 않은 행렬을 만들어준다.

In [121]:
e = np.empty((4,2))

In [122]:
e

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 7.17383318e-321],
       [8.34451927e-308, 1.33511969e-306]])

#### 특정 값 뽑아내기
- sequence type이므로 indexing 방법으로 접근 가능
    - indexing 방법이 조금 특이

In [125]:
a = np.arange(10).reshape(2,5)

In [126]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

파이썬 방식

In [127]:
a[1][3]

8

넘파이 방식(좀 더 고급적) [행, 열]
- 특정 열, 행 뽑아내는 것을 편하게 할 수 있다.
- 5가지 인덱싱 방법 지원

1. 콤마(,)

In [128]:
a[1,3]

8

In [129]:
a[:,3]

array([3, 8])

In [130]:
a = np.arange(27).reshape(3,3,3)

In [141]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

생략되어있으면 알아서 전체 가져온다.

In [134]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [135]:
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

2. ... : 전부 다 가져온다. (지원해준다.)

In [136]:
a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [142]:
a[:, :, 1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

3. 조건을 이용할 수 있다.
    - & : and
    - | : or

In [143]:
a = np.arange(10)

In [148]:
a[(a>3) & (a<8)]

array([4, 5, 6, 7])

In [149]:
a[(a>3) | (a<8)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4. 마스킹 기법
    - True인 것만 뽑아낸다.

In [151]:
a[[True, False, True, True, True, True, True, True, True, True]]

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

조건 - 마스킹으로 되어있다.

In [152]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

5. 팬시인덱싱
    - 행 뽑을 때 사용
    - a[[1,2]] : 1행, 2행을 뽑는다.

In [163]:
a = np.arange(10).reshape(5,2)

In [155]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [156]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

In [158]:
a[[1,3]][:,1]

array([3, 7])

다양한 방법으로 인덱싱 슬라이싱이 가능하다.

a[[1,2],[2,3]] -> a[1,2], a[2,3]

### numpy에서 for 쓰면 싸대기
- vectorize 기법에 어긋남

In [164]:
b = np.nditer(a)

In [173]:
next(b)

array(7)

함수를 잘 고려해서 만들어야 한다.

In [174]:
def add_(a,b):
    return a+b

In [175]:
x = np.arange(5)
y = np.arange(5)

In [176]:
add_(x,y)

array([0, 2, 4, 6, 8])

In [177]:
x

array([0, 1, 2, 3, 4])

In [178]:
x*3

array([ 0,  3,  6,  9, 12])

#### 브로드캐스팅
- 간단한 크기는 알아서 맞춰진다.
- 복잡한 구조는 못 맞춰줌 -> 브로드캐스팅 에러

In [179]:
x+3

array([3, 4, 5, 6, 7])

In [180]:
3 + np.arange(10)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [181]:
np.array([1,2]) + np.arange(10)

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

#### ufunc 유니버셜 함수
- 보편적 함수
- Python에 있는 함수는 대부분 있다.
- type(ufunc)하면 ufunc 나옴
- 값을 동시에 여러개 넣어도 되고 하나만 넣어도 된다.
- shift+tab으로는 설명 부실 -> 보는 방법 np.info()

절대값

파이썬 기본 함수

In [182]:
abs(-1)

1

In [183]:
abs([-1,-2,3])

TypeError: bad operand type for abs(): 'list'

넘파이 함수

In [184]:
np.abs(-1)

1

In [185]:
np.abs([-1,-2,3])

array([1, 2, 3])

올림 함수

In [186]:
np.ceil([2.9, 1, 2, 3, 0.3])

array([3., 1., 2., 3., 1.])

np 정보 보는 법. np.info()

In [187]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [188]:
from scipy.special import factorial

In [191]:
factorial([3,4,5])

array([  6.,  24., 120.])

scipy도 numpy로 만들어서 numpy info로 볼 수 있다.

In [192]:
np.info(factorial)

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


#### np.where : 조건 ★★★
- 왜 중요한가? : 

In [198]:
b = np.arange(5,10)

그냥 쓰면 조건에 해당하는 것의 인덱스를 보여준다.

In [199]:
np.where(b>5)

(array([1, 2, 3, 4], dtype=int64),)

In [200]:
b[np.where(b>5)]

array([6, 7, 8, 9])

조건에 맞는 것은 0, 안 맞는것은 1로 나타내라고 설정

In [197]:
np.where(b>5, 0, 1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

가장 큰 수

In [201]:
np.max(b)

9

가장 큰 수의 인덱스
- arg 붙으면 그 값의 인덱스가 어디인지 알려준다.

ufunc는 함수처럼 사용할 수도 있고 메서드처럼 사용할 수도 있다.
- 대부분 지원하지만 가끔 지원하지 않는 것도 있다.

In [202]:
np.argmax(b)

4

In [204]:
np.argmin(b)

0

In [205]:
b.argmin()

0

In [206]:
b.argmax()

4

pi
- 넘파이 파이와 파이썬의 파이와 값이 같다.
- 임포트할 때 매쓰도 임포트하면 메모리에 올라가서 효율이 떨어지니까 넘파이에 넣고 사용

In [207]:
from numpy import pi
from math import pi as mpi

In [210]:
pi

3.141592653589793

In [209]:
mpi

3.141592653589793

In [211]:
pi is mpi

False

In [212]:
pi == mpi

True

파이썬에 ... 정의되어있다.
- 실수 많이 하므로 사용하지 말것

In [213]:
type(...)

ellipsis

In [214]:
dir(...)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

np.nan 골치 아픔 :(
- float('nan')과 다름....!:O
- 외울 수 밖에 없다

In [215]:
np.nan

nan

In [220]:
t = float('nan')

In [217]:
np.nan == float('nan')

False

In [222]:
np.set_printoptions(threshold=t)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

np.newaxis 도 골치아픔...:O
- 외워야 한다.

In [224]:
np.newaxis == None

True

@ 연산은 행렬 곱이다. Python3.6부터 나옴 

A.dot(B) : 내적 -> 행렬 곱과 같음

#### 넘파이에서의 copy()
- 외우고 있어야함 :)
- python에서의 카피와 좀 다르다.
    - 파이썬 : 스왈로우 카피
    - 넘파이 : 딥카피
- 스왈로우 카피는 view()이다.
- 원본을 보존하기 위해 copy 사용한다.

In [225]:
a = np.arange(10).reshape(2,5)

In [226]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [227]:
b = a

In [228]:
a[0][0] = 100

In [229]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [230]:
b

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

파이썬에서 copy는 스왈로우 카피였다. <-> 넘파이는 기본적으로 딥카피이다.

In [231]:
c = b.copy()

In [232]:
b[0][0] = - 100

In [233]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [234]:
c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [235]:
c = b.view()

In [236]:
b[0][0] = - 100

In [237]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [238]:
c

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])